# Generated by Django 2.1.7 on 2019-06-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_work',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='not_solve',
            field=models.IntegerField(default=0),
        ),
    ]
