# Generated by Django 2.1.7 on 2019-06-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190607_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_exam',
            field=models.BooleanField(default=False),
        ),
    ]
