# Generated by Django 2.1.7 on 2019-06-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20190607_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('F', '填空'), ('C', '选择'), ('J', '判断')], default='C', max_length=32),
        ),
    ]
