# Generated by Django 2.1.7 on 2019-06-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20190607_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_a',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='question',
            name='question_b',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='question',
            name='question_c',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='question',
            name='question_d',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
