# Generated by Django 2.1.7 on 2019-06-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20190607_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_a',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_b',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_c',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_d',
            field=models.CharField(default='', max_length=128),
        ),
    ]
