# Generated by Django 2.1.7 on 2019-06-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20190607_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_a',
            field=models.CharField(default='无', max_length=64),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_b',
            field=models.CharField(default='无', max_length=64),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_c',
            field=models.CharField(default='无', max_length=64),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_d',
            field=models.CharField(default='无', max_length=64),
        ),
    ]
